version: '3.9'

services:
  web:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "3050:80"
      - "30443:443"
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config: